setwd('/home/lgm-upch/Desktop/coronavirus/Ago26/ncov/my_profiles/lambda/')
library(dplyr)
library(tidyverse)
input<- read.table("1632114232707.metadata.tsv", header = T, sep = "\t", stringsAsFactors = FALSE)
ncol(input)
#head(input)

output <- input
colnames(output)
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencia Nacional de Biotecnología y Biología Molecular. Instituto Nacional de Salud Perú"] <- "INS Peru. Laboratorio de Referencia Nacional de Biotecnologia y Biología Molecular."
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencia Nacional de Enteropatógenos. Instituto Nacional de Salud del Perú"] <- "INS Peru. Laboratorio de Referencia Nacional de Enteropatogenos."
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencia Nacional de Biotecnología y Biología Molecular. Instituto Nacional de Salud Peru"] <- "INS Peru. Laboratorio de Referencia Nacional de Biotecnologia y Biología Molecular."
output$submitting_lab[output$submitting_lab== "Laboratorio de Genómica Microbiana, Universidad Peruana Cayetano Heredia"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencia Nacional de Biotecnologia y Biologia Molecular.Instituto Nacional de Salud.Peru"] <- "INS Peru. Laboratorio de Referencia Nacional de Biotecnologia y Biología Molecular."
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencia Nacional de Biotecnología y Biología Molecular. Instituto Nacional de Salud."] <- "INS Peru. Laboratorio de Referencia Nacional de Biotecnologia y Biología Molecular."
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencia Nacional de Biotecnología y Biología Molecular. Instituto Nacional de Salud.Perú"] <- "INS Peru. Laboratorio de Referencia Nacional de Biotecnologia y Biología Molecular."
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencia Nacional de Biotecnologia y Biologia Molecular. Instituto Nacional de Salud Peru"] <- "INS Peru. Laboratorio de Referencia Nacional de Biotecnologia y Biología Molecular."
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencia Nacional de Biotecnología y Biología Molecular. Instituto Nacional de Salud Perú."] <- "INS Peru. Laboratorio de Referencia Nacional de Biotecnologia y Biología Molecular."
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencia Nacional de Biotecnologia y Biologia Molecular.Instituto Nacional de Salud.Perú"] <- "INS Peru. Laboratorio de Referencia Nacional de Biotecnologia y Biología Molecular."
output$submitting_lab[output$submitting_lab== "Laboratorio de Infecciones Respiratorias Agudas"] <- "INS Peru. Laboratorio de Infecciones Respiratorias Agudas. Centro Nacional de Salud Publica."
output$submitting_lab[output$submitting_lab== "Laboratorio de Infecciones Respiratorias Agudas. Centro Nacional de Salud Publica,Instituto Nacional de Salud"] <- "INS Peru. Laboratorio de Infecciones Respiratorias Agudas. Centro Nacional de Salud Publica."
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencia Nacional de Biotecnología y Biología Molecular. Centro Nacional de Salud Publica. Instituto Nacional de Salud Peru."] <- "INS Peru. Laboratorio de Referencia Nacional de Biotecnologia y Biología Molecular."
output$submitting_lab[output$submitting_lab== "LLaboratorio de Infecciones Respiratorias Agudas. Centro Nacional de Salud Publica. Instituto Nacional de Salud del Peru"] <- "INS Peru. Laboratorio de Infecciones Respiratorias Agudas. Centro Nacional de Salud Publica."
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencial Nacional de Virus Respiratorios"] <- "INS Peru. Laboratorio de Referencia Nacional de Virus Respiratorios." 
output$submitting_lab[output$submitting_lab== "Centro de Investigaciones Tecnológicas, Biomédicas y Medioambientales (CITBM)"] <- "UNMSM. Centro de Investigaciones Tecnologicas, Biomedicas y Medioambientales (CITBM)"
output$submitting_lab[output$submitting_lab== "Faculty of Veterinary Medicine, Universidad Peruana Cayetano Heredia"] <- "UPCH. Facultad de Medicina Veterinaria."
output$submitting_lab[output$submitting_lab== "Pathogen Discovery, Respiratory Viruses Branch, Division of Viral Diseases, Centers for Disease Control and Prevention"] <- "CDC. Respiratory Viruses Branch, Division of Viral Diseases."
output$submitting_lab[output$submitting_lab== "Genomics and Discovery, Respiratory Viruses Branch, Division of Viral Diseases, Centers for Disease Control and Prevention"] <- "CDC. Respiratory Viruses Branch, Division of Viral Diseases."
output$submitting_lab[output$submitting_lab== "Laboratorio de Referencia Nacional de Virus Respiratorios. Centro Nacional de Salud Publica. Instituto Nacional de Salud Peru."] <- "INS Peru. Laboratorio de Referencia Nacional de Virus Respiratorios."

output$submitting_lab[output$submitting_lab== "cov0954"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0947"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0948"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0949"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0951"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0952"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0953"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0974"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0943"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0944"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0945"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0946"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0955"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0957"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0958"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0973"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0960"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0961"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0962"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0963"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0964"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0965"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0966"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0968"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0971"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0972"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0975"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0976"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0956"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0959"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0970"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0729"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0682"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0813"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0804"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0936"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0891"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0911"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0893"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0892"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0904"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0907"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0883"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0884"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0885"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0886"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0887"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0888"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0889"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0890"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0894"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0896"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0898"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0900"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0902"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0903"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0906"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0908"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0909"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0912"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0913"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0916"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0920"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0921"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0923"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0924"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0925"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0926"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0897"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0899"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0901"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0905"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0910"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0922"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0927"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0929"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0915"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0918"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0928"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0914"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0917"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0895"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0938"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0939"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0950"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0967"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0969"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0940"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0933"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0942"] <- "UPCH. Laboratorio de Genomica Microbiana."
output$submitting_lab[output$submitting_lab== "cov0937"] <- "UPCH. Laboratorio de Genomica Microbiana."

output$division[output$division== "Huánuco"] <- "Huanuco"

table(output$submitting_lab)
table(output$division)
output$division[output$division== ""] <- "Lima"

table(output$Nextstrain_clade)
table(output$pangolin_lineage)
output$variant=output$pangolin_lineage
output$variant[output$variant== "C.37"]<-"Lambda"
output$variant[output$variant== "C.37.1"]<-"Lambda"
output$variant[output$variant== "P.1"]<-"Gamma"
output$variant[output$variant== "P.1.1"]<-"Gamma"
output$variant[output$variant== "P.1.2"]<-"Gamma"
output$variant[output$variant== "P.1.3"]<-"Gamma"
output$variant[output$variant== "P.1.4"]<-"Gamma"
output$variant[output$variant== "P.1.7"]<-"Gamma"
output$variant[output$variant== "B.1.1.7"]<-"Alpha"
output$variant[output$variant== "B.1.617.1"]<-"Kappa"
output$variant[output$variant== "B.1.617.2"]<-"Delta"
output$variant[output$variant== "AY.11"]<-"Delta"
output$variant[output$variant== "AY.12"]<-"Delta"
output$variant[output$variant== "AY.20"]<-"Delta"
output$variant[output$variant== "AY.21"]<-"Delta"
output$variant[output$variant== "AY.23"]<-"Delta"
output$variant[output$variant== "AY.3"]<-"Delta"
output$variant[output$variant== "AY.3.1"]<-"Delta"
output$variant[output$variant== "AY.9"]<-"Delta"
output$variant[output$variant== "AY.4"]<-"Delta"
output$variant[output$variant== "AY.7.1"]<-"Delta"
output$variant[output$variant== "AY.25"]<-"Delta"
output$variant[output$variant== "B.1.621"]<-"Mu"
output$variant[output$variant== "B.1.525"]<-"Eta"
output$variant[output$variant== "B.1.526"]<-"Iota"
output$variant[output$variant== "B.1.621.1"]<-"Mu"
#output[grepl(".",output$variant),output$variant := "Other"]
output$variant<-gsub("[BC]", "Other", (gsub("\\.", "", output$variant)))
output$variant<-gsub("Other.*", "Other", output$variant)
output$variant[output$variant== "A1"]<-"Other"
output$variant[output$variant== "A2"]<-"Other"
output$variant[output$variant== "A3"]<-"Other"
output$variant[output$variant== "A5"]<-"Other"
output$variant[output$variant== "A"]<-"Other"
output$variant[output$variant== "N4"]<-"Other"
output$variant[output$variant== "P2"]<-"Other"
output$variant[output$variant== "None"]<-"Other"
table(output$variant)

write.table(output, file = 'metadata.lambda.tsv', quote = F, row.names = F, sep = "\t")